GamCollezioni/GamCollezioni/Models/ErrorViewModel.cs
namespace GamCollezioni.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GamCollezioni/GamCollezioni/Models/GemCollezioniContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GamCollezioni.Models;

public partial class GemCollezioniContext : DbContext
{
    public GemCollezioniContext()
    {
    }

    public GemCollezioniContext(DbContextOptions<GemCollezioniContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Opera> Opere { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Server=localhost\\SQLEXPRESS;Database=GemCollezioni;Trusted_Connection=True;TrustServerCertificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Opera>(entity =>
        {
            entity.ToTable("Opera");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

GamCollezioni/GamCollezioni/Models/Opera.cs
using System;
using System.Collections.Generic;

namespace GamCollezioni.Models;

public partial class Opera
{
    public int Id { get; set; }

    public string? Autore { get; set; }

    public string? Titolo { get; set; }

    public string? Datazione { get; set; }

    public string? Tecnica { get; set; }

    public string? Dimensioni { get; set; }

    public string? Immagine { get; set; }
}

GamCollezioni/GamCollezioni/Controllers/HomeController.cs
using GamCollezioni.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GamCollezioni.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GamCollezioni/GamCollezioni/Controllers/OpereController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GamCollezioni.Models;
using Microsoft.AspNetCore.Authorization;

namespace GamCollezioni.Controllers
{
    [Authorize]
    public class OpereController : Controller
    {
        private readonly GemCollezioniContext _context;

        public OpereController(GemCollezioniContext context)
        {
            _context = context;
        }

        // GET: Opere
        [AllowAnonymous]
        public async Task<IActionResult> Index(int pagina, string autore, string titolo)
        {
            var record = 10;
            if (pagina == 0)
                pagina = 1;
            var lista = _context.Opere.IgnoreQueryFilters();
            if(!string.IsNullOrEmpty(autore))
                lista = lista.Where(x => x.Autore!.Contains(autore));
            if(!string.IsNullOrEmpty(titolo))
                lista =lista.Where(x => x.Titolo!.Contains(titolo));
            ViewBag.Autore = autore;
            ViewBag.Titolo = titolo;
            ViewBag.Pagine = lista.Count() / record;
            ViewBag.PaginaSeke = pagina;//numero di pagine da visualizzare


            return View(await lista.Skip((pagina-1)*record).Take(record).ToListAsync());
        }
        [AllowAnonymous]
        public async Task<IActionResult> Autori()
        {
          
            var lista = await _context.Opere.Select(x=>x.Autore).Distinct().ToArrayAsync();
            


            return View(lista);
        }

        // GET: Opere/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var opera = await _context.Opere
                .FirstOrDefaultAsync(m => m.Id == id);
            if (opera == null)
            {
                return NotFound();
            }

            return View(opera);
        }

        // GET: Opere/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Opere/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Autore,Titolo,Datazione,Tecnica,Dimensioni,Immagine")] Opera opera)
        {
            if (ModelState.IsValid)
            {
                _context.Add(opera);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(opera);
        }

        // GET: Opere/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var opera = await _context.Opere.FindAsync(id);
            if (opera == null)
            {
                return NotFound();
            }
            return View(opera);
        }

        // POST: Opere/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Autore,Titolo,Datazione,Tecnica,Dimensioni,Immagine")] Opera opera)
        {
            if (id != opera.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(opera);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OperaExists(opera.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(opera);
        }

        // GET: Opere/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var opera = await _context.Opere
                .FirstOrDefaultAsync(m => m.Id == id);
            if (opera == null)
            {
                return NotFound();
            }

            return View(opera);
        }

        // POST: Opere/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var opera = await _context.Opere.FindAsync(id);
            if (opera != null)
            {
                _context.Opere.Remove(opera);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OperaExists(int id)
        {
            return _context.Opere.Any(e => e.Id == id);
        }
    }
}

GamCollezioni/GamCollezioni/Views/Opere/Autori.cshtml
@model IEnumerable<string>

@{
    ViewData["Title"] = "Autori";
}

<h1>Elenco Autori</h1>
<p>

    @{
        var pattern = "ABCDEFGHIJKLMNOPQRSTUVXWYZ";
        for(int i = 0; i< pattern.Length; i++)
        {
            <th>
                <td>  <a><b>@pattern[i]</b></a></td>
            </th>
            
            <br />
            foreach(var item in Model)
            {
                if (item.StartsWith(pattern[i]))
                {
                    <a href="/Opere/index?autore=@item">@item <br /></a>
                }
            }
            <br />
            <hr />
            <br />
        }
    }

GamCollezioni/GamCollezioni/Views/Opere/Create.cshtml
@model GamCollezioni.Models.Opera

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Opera</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Autore" class="control-label"></label>
                <input asp-for="Autore" class="form-control" />
                <span asp-validation-for="Autore" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titolo" class="control-label"></label>
                <input asp-for="Titolo" class="form-control" />
                <span asp-validation-for="Titolo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datazione" class="control-label"></label>
                <input asp-for="Datazione" class="form-control" />
                <span asp-validation-for="Datazione" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tecnica" class="control-label"></label>
                <input asp-for="Tecnica" class="form-control" />
                <span asp-validation-for="Tecnica" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dimensioni" class="control-label"></label>
                <input asp-for="Dimensioni" class="form-control" />
                <span asp-validation-for="Dimensioni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Immagine" class="control-label"></label>
                <input asp-for="Immagine" class="form-control" />
                <span asp-validation-for="Immagine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GamCollezioni/GamCollezioni/Views/Opere/Delete.cshtml
@model GamCollezioni.Models.Opera

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Opera</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autore)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autore)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titolo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titolo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datazione)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datazione)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tecnica)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tecnica)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dimensioni)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dimensioni)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Immagine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Immagine)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GamCollezioni/GamCollezioni/Views/Opere/Details.cshtml
@model GamCollezioni.Models.Opera

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Opera</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autore)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autore)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titolo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titolo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datazione)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datazione)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tecnica)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tecnica)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dimensioni)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dimensioni)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Immagine)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Model.Immagine title=@Model.Titolo" alt="@Model.Immagine" />
            @* Html.DisplayFor(model => model.Immagine)*@
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GamCollezioni/GamCollezioni/Views/Opere/Edit.cshtml
@model GamCollezioni.Models.Opera

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Opera</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Autore" class="control-label"></label>
                <input asp-for="Autore" class="form-control" />
                <span asp-validation-for="Autore" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titolo" class="control-label"></label>
                <input asp-for="Titolo" class="form-control" />
                <span asp-validation-for="Titolo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datazione" class="control-label"></label>
                <input asp-for="Datazione" class="form-control" />
                <span asp-validation-for="Datazione" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tecnica" class="control-label"></label>
                <input asp-for="Tecnica" class="form-control" />
                <span asp-validation-for="Tecnica" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dimensioni" class="control-label"></label>
                <input asp-for="Dimensioni" class="form-control" />
                <span asp-validation-for="Dimensioni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Immagine" class="control-label"></label>
                <input asp-for="Immagine" class="form-control" />
                <span asp-validation-for="Immagine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GamCollezioni/GamCollezioni/Views/Opere/Index.cshtml
@model IEnumerable<GamCollezioni.Models.Opera>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <form>
        Cerca per autore:<input type="text" name="autore"  value="@ViewBag.Autore"/>
        Cerca per Titolo:<input type="text" name="titolo" value="@ViewBag.Titolo"/>
        <input type="submit" value="Cerca" />
    </form>
   
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Autore)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titolo)
            </th>
          
            <th>
                @Html.DisplayNameFor(model => model.Tecnica)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Autore)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titolo)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.Tecnica)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<p>
@for(int i = 1; i<=ViewBag.Pagine; i++)
{
        if (ViewBag.PaginaSele == i)
        {
            <a><b>@i</b></a>
        }
        else
        {
            <a href="/Opere/?pagina=@i&autore=@ViewBag.Autore&titolo=@ViewBag.Titolo">@i</a>
        }

}
</p>

GamCollezioni/GamCollezioni/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GamCollezioni</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GamCollezioni.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GamCollezioni</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Opere" asp-action="Index">Opere</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Opere" asp-action="Autori">Autori</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GamCollezioni - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>